name: backend-cd

on:
  push:
    branches: ["main"]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  Linting:
    name: Linting Job
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Set up pipenv
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install python3 python3-pip -y
          pip install --user pipenv
          echo 'export PATH=$PATH:~/.local/bin' >> ~/.bashrc
          source ~/.bashrc
          pipenv --version

      - name: Cache Pipenv Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('backend/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install Dependency
        working-directory: backend
        run: pipenv install --dev

      - name: Linting Job
        working-directory: backend
        run:  pipenv run lint
        continue-on-error: false

  Test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Set up pipenv
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install python3 python3-pip -y
          pip install --user pipenv
          echo 'export PATH=$PATH:~/.local/bin' >> ~/.bashrc
          source ~/.bashrc
          pipenv --version

      - name: Cache Pipenv Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('backend/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install Dependency
        working-directory: backend
        run: pipenv install

      - name: Run Test
        working-directory: backend
        run: pipenv run test
        continue-on-error: false

  Build:
    name: Build Job
    runs-on: ubuntu-latest
    needs:
      - Linting
      - Test
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Image and Push
        working-directory: backend
        run: |
          GIT_SHA=$(git rev-parse --short HEAD)
          docker build --tag=backend:${GIT_SHA} .
          REPOSITORY_URI=$(aws ecr describe-repositories --repository-names backend --region us-east-1 --query "repositories[0].repositoryUri" --output text)
          docker tag backend:${GIT_SHA} $REPOSITORY_URI:${GIT_SHA}
          docker push $REPOSITORY_URI:${GIT_SHA}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  Deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs:
      - Build
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: EKS config
        run: |
          aws eks update-kubeconfig --name cluster --region us-east-1

      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

      - name: Check Kubectl
        run: kubectl get pods

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy
        working-directory: backend/k8s
        run: |
          GIT_SHA=$(git rev-parse --short HEAD)
          kustomize edit set image backend=399608680309.dkr.ecr.us-east-1.amazonaws.com/backend:$GIT_SHA
          kustomize build | kubectl apply -f -

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}        

