name: CI

on:
  push:
    branches: ["main"]
    paths:
      - 'frontend/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  Linting:
    name: Linting Job
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Install Dependency
        working-directory: frontend
        run: npm install
      - name: Linting Job
        working-directory: frontend
        run:  npm run lint
        continue-on-error: false

  Test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Use Correct NodeJS Version
        working-directory: frontend
        run: nvm use
      - name: Install Dependency
        working-directory: frontend
        run: npm ci
      - name: Run Test
        working-directory: frontend
        run: npm test
        continue-on-error: false

  Build:
    name: Build Job
    runs-on: ubuntu-latest
    needs:
      - Linting
      - Test
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Build
        run: echo "This is a build job"
      

