name: frontend-cd

on:
  push:
    branches: ["main"]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  Linting:
    name: Linting Job
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Dependency
        working-directory: frontend
        run: npm ci

      - name: Linting Job
        working-directory: frontend
        run:  npm run lint
        continue-on-error: false

  Test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Set Up Nvm
        working-directory: frontend
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash

      - name: Use Correct NodeJS Version
        working-directory: frontend
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install
          nvm use

      - name: Cache
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Dependency
        working-directory: frontend
        run: npm ci

      - name: Run Test
        working-directory: frontend
        run: npm test
        continue-on-error: false

  Build:
    name: Build Job
    runs-on: ubuntu-latest
    needs:
      - Linting
      - Test
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Image and Push
        working-directory: frontend
        run: |
          GIT_SHA=$(git rev-parse --short HEAD)
        docker build --build-arg REACT_APP_MOVIE_API_URL=http://af92714e44e434dcd86b6d6de76ee433-1744019683.us-east-1.elb.amazonaws.com  --tag=frontend:${GIT_SHA} .
          REPOSITORY_URI=$(aws ecr describe-repositories --repository-names frontend --region us-east-1 --query "repositories[0].repositoryUri" --output text)
          docker tag frontend:${GIT_SHA} $REPOSITORY_URI:${GIT_SHA}
          docker push $REPOSITORY_URI:${GIT_SHA}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  Deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs:
      - Build
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: EKS config
        run: |
          aws eks update-kubeconfig --name cluster --region us-east-1

      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

      - name: Check Kubectl
        run: kubectl get pods

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy
        working-directory: frontend/k8s
        run: |
          GIT_SHA=$(git rev-parse --short HEAD)
          kustomize edit set image frontend=399608680309.dkr.ecr.us-east-1.amazonaws.com/frontend:$GIT_SHA
          kustomize build | kubectl apply -f -

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}        

